package ch.steigis.overprint.domain.model

/** One calendar day's wellness totals. Timeseries samples will live in a separate table later. */
data class DailyHealth(
    val date: String,
    val steps: Double? = null,
    val stepGoal: Double? = null,
    val distanceMeters: Double? = null,
    val caloriesTotal: Double? = null,
    val caloriesActive: Double? = null,
    val caloriesBmr: Double? = null,
    val restingHr: Double? = null,
    val minHr: Double? = null,
    val maxHr: Double? = null,
    val sleepSeconds: Double? = null,
    val sleepScore: Double? = null,
    val sleepDeepSeconds: Double? = null,
    val sleepLightSeconds: Double? = null,
    val sleepRemSeconds: Double? = null,
    val sleepAwakeSeconds: Double? = null,
    val intensityModerate: Double? = null,
    val intensityVigorous: Double? = null,
    val stressAvg: Double? = null,
    val stressMax: Double? = null,
    val bodyBatteryCharged: Double? = null,
    val bodyBatteryDrained: Double? = null,
    val bodyBatteryHigh: Double? = null,
    val bodyBatteryLow: Double? = null,
    val bodyBatteryLatest: Double? = null,
    val floorsUp: Double? = null,
    val floorsDown: Double? = null,
    val spo2Avg: Double? = null,
    val spo2Min: Double? = null,
    val respirationAvg: Double? = null,
    val respirationMin: Double? = null,
    val respirationMax: Double? = null,
    val updatedAtMillis: Long = 0L,
)
